AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Example Pet Store API with SpringBoot
Parameters:
  ServiceName:
    Description: Service name
    Type: String
  ServiceVersion:
    Description: Service version
    Type: String
  ServiceEnvironment:
    Description: Service environment
    Type: String
Globals:
  Api:
    EndpointConfiguration: REGIONAL
Resources:
  PetstoreApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
  PetStoreFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${ServiceName}-${ServiceEnvironment}
      Description: Petstore Demo API
      Handler: com.sd.demo.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri:
        Fn::Sub: ./build/distributions/${ServiceName}-${ServiceVersion}.zip
      MemorySize: 1512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 60
      Events:
        GetAllPets:
          Type: Api
          Properties:
            Path: /pets
            Method: get
            RestApiId:
              Ref: PetstoreApi
        GetPetDetails:
          Type: Api
          Properties:
            Path: /pets/{id}
            Method: get
            RestApiId:
              Ref: PetstoreApi
        CreatePet:
          Type: Api
          Properties:
            Path: /pets
            Method: post
            RestApiId:
              Ref: PetstoreApi
Outputs:
  SpringBootPetStoreApi:
    Description: URL for application
    Value:
      Fn::Sub: https://${PetstoreApi}.execute-api.${AWS::Region}.amazonaws.com/pets
    Export:
      Name: SpringBootPetStoreApi
