parameters:

  - name: serviceName
    displayName: Service name
    type: string
    
  - name: serviceVersion
    displayName: Service version
    type: string    

  - name: environments
    displayName: List of environments
    type: object
    default: []

stages:

  - stage: Build
    jobs:
      - template: azure-build.yml

  - ${{ each environment in parameters.environments }}:
    - stage: Deploy_${{upper(replace(environment.name, '-', '_'))}}
      jobs:
        - template: azure-deploy.yml
          parameters:
            jobName: Deploy
            serviceName: ${{parameters.serviceName}}
            serviceVersion: ${{parameters.serviceVersion}}
            serviceEnv: ${{environment.name}}
            awsArtifactBucket: api-sam-s3
            awsCredentials: aws_sandbox
            awsRegion: ${{environment.awsRegion}}
            awsRoleArn: arn:aws:iam::${{environment.awsAccount}}:role/${{environment.awsRoleName}}